#!/bin/bash
#
# node
#
# chkconfig: - 85 15
# description: start, stop, restart reporter
#              
# started by monit

RETVAL=0

case "$1" in
    start)
      cd /pipeline/bin && /pipeline/bin/node_startup.rb & >> /pipeline/crash.log
      RETVAL=$?
  ;;
    stop)
      kill -9 `cat /pipeline/node.pid`
      rm /pipeline/node.pid
      RETVAL=$?
  ;;
    restart)
    kill -9 `cat /pipeline/node.pid`
    rm /pipeline/node.pid
      cd /pipeline/bin && /pipeline/bin/node_startup.rb & >> /pipeline/crash.log
      RETVAL=$?
  ;;
    *)
      echo "Usage: node {start|stop|restart}"
      exit 1
  ;;
esac      

exit $RETVAL
